version: 2

project_name: nanoproxy

dist: dist

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: '{{ incpatch .Version }}-next'

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: nanoproxy
    binary: nanoproxy
    ldflags:
      - -s -w
      - -X nanoproxy.version={{.Version}}
      - -X nanoproxy.commit={{.Commit}}
      - -X nanoproxy.date={{ .CommitDate }}
      - -X nanoproxy.builtBy=goreleaser
      - -X nanoproxy.treeState={{ .IsGitDirty }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc
  groups:
    - title: "Dependency updates"
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: "Build process updates"
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: "Other work"
      order: 9999
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

dockers_v2:
  - id: nanoproxy
    images:
      - "ghcr.io/ryanbekhen/nanoproxy"
    tags:
      - "latest"
      - "{{ .Version }}"
    dockerfile: Dockerfile
    labels:
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/ryanbekhen/nanoproxy/main/README.md"
      "io.artifacthub.package.maintainers": "[{\"name\":\"Achmad Irianto Eka Putra\",\"email\":\"i@ryanbekhen.dev\"}]"
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.description": "Nanoproxy is a simple proxy written in Go."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    extra_files:
      - supervisord.conf

  - id: nanoproxy-tor
    images:
      - "ghcr.io/ryanbekhen/nanoproxy-tor"
    tags:
      - "latest"
      - "{{ .Version }}"
    dockerfile: Dockerfile-tor
    labels:
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/ryanbekhen/nanoproxy/main/README.md"
      "io.artifacthub.package.maintainers": "[{\"name\":\"Achmad Irianto Eka Putra\",\"email\":\"i@ryanbekhen.dev\"}]"
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.description": "Nanoproxy is a simple proxy written in Go."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - "linux/amd64"
    extra_files:
      - supervisord.conf

archives:
  - id: default
    ids:
      - nanoproxy
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE


homebrew_casks:
  - name: nanoproxy
    repository:
      owner: ryanbekhen
      name: homebrew-nanoproxy
    directory: Casks
    homepage: https://github.com/ryanbekhen/nanoproxy
    description: "Simple Socks5 Proxy written in Go"
    license: "MIT"
    hooks:
      post:
        install: |
          bin.install "nanoproxy"

winget:
  - name: nanoproxy
    publisher: ryanbekhen
    license: MIT
    homepage: https://github.com/ryanbekhen/nanoproxy
    short_description: "Simple Socks5 Proxy written in Go"
    tags:
      - Proxy
      - Socks5
    repository:
      owner: ryanbekhen
      name: nanoproxy-winget-pkgs
      branch: "nanoproxy-{{ .Version }}"
      pull_request:
        enabled: true
        draft: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

nfpms:
  - id: packages
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/ryanbekhen/nanoproxy
    description: "Simple Socks5 Proxy written in Go"
    maintainer: "Achmad Irianto Eka Putra <i@ryanbekhen.dev>"
    license: "MIT"
    vendor: ryanbekhen
    bindir: /usr/bin
    section: utils
    contents:
      - src: systemd/nanoproxy.service
        dst: /etc/systemd/system/nanoproxy.service
        type: "config|noreplace"
      - src: config/nanoproxy
        dst: /etc/nanoproxy/nanoproxy
        type: "config|noreplace"
    formats:
      - deb
      - rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/ryanbekhen/

release:
  name_template: "{{ .Version }}"