FROM alpine:3.21

RUN apk update && \
    apk add --no-cache tor

COPY nanoproxy /usr/bin/nanoproxy
COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

RUN mkdir -p /etc/tor && \
    echo -e "ControlPort 9051\nCookieAuthentication 0" > /etc/tor/torrc

RUN mkdir -p /var/lib/tor

EXPOSE 1080

USER tor

ENTRYPOINT ["/bin/sh", "-c", "/usr/bin/entrypoint.sh"]