# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoproxy < Formula
  desc "nanoproxy is a simple reverse proxy written in Go."
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.3/nanoproxy_darwin_arm64.tar.gz"
      sha256 "b02e7d71982dec548ea72b8f9d8263837835f8736a6b954c059bf4c7255a15c5"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.3/nanoproxy_darwin_amd64.tar.gz"
      sha256 "3ca310d9cd69819a599ee500c9091449443d9637c2b49515a62be46cf9166450"

      def install
        bin.install "nanoproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.3/nanoproxy_linux_arm64.tar.gz"
      sha256 "06696008f091f5db2214c78d746176aab733559c4b3058a1fdea68a2b34517b1"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.3/nanoproxy_linux_amd64.tar.gz"
      sha256 "a613e441d28f395c4dba726c6f6012f2739fb57c769e87e05647d255905ebd36"

      def install
        bin.install "nanoproxy"
      end
    end
  end
end
