# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoproxy < Formula
  desc "nanoproxy is a simple reverse proxy written in Go."
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.2/nanoproxy_darwin_amd64.tar.gz"
      sha256 "e5e87c79e01a8553a9277079b3d5a5af758fb42dfed790ace64a532c3472b4ad"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.2/nanoproxy_darwin_arm64.tar.gz"
      sha256 "19cdb953e62aa01f00aeb9db731ea36c88738c4bd03de23a28bf79f201c82b12"

      def install
        bin.install "nanoproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.2/nanoproxy_linux_amd64.tar.gz"
      sha256 "a05604d35f9f88b6619309ceb08c66b02fdfd2c7450cfd787555f664c5b32169"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.8.2/nanoproxy_linux_arm64.tar.gz"
      sha256 "7cf23a796604c5157c3524223965be79c238f7a55349fb9cead19f4d23941080"

      def install
        bin.install "nanoproxy"
      end
    end
  end
end
